name: 'Setup Python Environment'
description: 'Configura Python y dependencias con cache'

runs:
  using: "composite"
  steps:
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Instalar dependencias
      shell: bash
      run: |
        python -m pip install --upgrade pip
        # Instalamos el paquete en modo editable y sus dependencias
        pip install -e .
        # Instalamos las herramientas de calidad y las dependencias que MyPy necesita explícitamente
        pip install black flake8 mypy pytest pytest-cov pydantic typer python-magic regex
